FROM python:3.7
WORKDIR /code
RUN pip install matplotlib
RUN pip install pandas
RUN pip install keras
RUN pip install tensorflow
RUN pip install sklearn
RUN pip install seaborn
CMD ["python","rapidminer.py"]